name: Test
on:
  push:
    branches: [ master ]
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'products.json'
      - 'Makefile'
      - '.github/workflows/test.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  build:
    name: Build & Validate
    if: ${{ !startsWith(github.head_ref, 'release-please--') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
      - name: Install lipo
        run: go install github.com/konoui/lipo@latest
      - name: Validate JSON
        run: |
          cat products.json | jq '.' >> /dev/null
      - name: go build
        run: make build
      - name: go vet
        run: go vet ./...
